os: Visual Studio 2015

environment:
  VisualStudioVersion: 14.0
  NuGetApiKey:
    secure: HFUEQanhaxHV/sRQYznQqg7LToxSGeIoSvrmyY29PJ1eDbXxUuYrEQ6MPAsZIQFT

configuration: Release

build_script:
  - ps: .\appveyor.ps1

artifacts:
  - path: OutputRoot\**\*
