version: 1.0.{build}
image: Visual Studio 2022
configuration: Release

init:
- pwsh: if(test-path -LiteralPath ./ci.build.init.ps1){. ./ci.build.init.ps1}

before_build:
  - dotnet restore

build:
  project: Sudoku.sln
  verbosity: normal

artifacts:
 - path: '**\nupkg\*.nupkg'
